amit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
    path('blog/<slug:slug>', post, name='post'),
    # path('search/', include('search.urls')),
    path('subscribe/', email_list_signup, name='subscribe'),
    path('tinymce/', include('tinymce.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.posts, name='posts'),
    path('tags/', views.tags, name='tags'),
    path('tags/<slug:tag>/', views.tagPage, name='tag'),
    #CRUD PATHS
    path('create_post/', views.createPost, name='create_post'),
    path('update_post/<slug:slug>/', views.updatePost, name='update_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from base.models import Profile
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
import readtime
# Create your models here.

class Signup(models.Model):
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

class Tag(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        ordering = ['name']
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.name)
            self.slug = slug
        super().save(*args, **kwargs)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to='images', default='/images/placeholder.png')
    body = RichTextUploadingField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    trending = models.BooleanField(default=False)
    latest = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.headline
    
    class Meta:
        ordering = ['-created']
        # unique_together = ('user',)
    
    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()
            
            self.slug = slug
        super().save(*args, **kwargs)

class PostComment(models.Model):
    # name = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=30, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    website = models.CharField(max_length=100, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.body
    
    @property
    def created_dynamic(self):
        now = timezone.now()
        return now
    

blog/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post, Signup

class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = '__all__'
        
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

class EmailSignupForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={
        "type": "email",
        "name": "email",
        "class": "form-control",
        "placeholder": "Type your email address",
    }), label="")

    class Meta:
        model = Signup
        fields = ('email', )

blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import *
from django.conf import settings
import readtime

from .models import *
from .forms import PostForm
from .filters import PostFilter

from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import EmailSignupForm
from .models import Signup

import json
import requests

MAILCHIMP_API_KEY = settings.MAILCHIMP_API_KEY
MAILCHIMP_DATA_CENTER = settings.MAILCHIMP_DATA_CENTER
MAILCHIMP_EMAIL_LIST_ID = settings.MAILCHIMP_EMAIL_LIST_ID

api_url = 'https://{dc}.api.mailchimp.com/3.0'.format(dc=MAILCHIMP_DATA_CENTER)
members_endpoint = '{api_url}/lists/{list_id}/members'.format(
    api_url=api_url,
    list_id=MAILCHIMP_EMAIL_LIST_ID
)


def subscribe(email):
    data = {
        "email_address": email,
        "status": "subscribed"
    }
    r = requests.post(
        members_endpoint,
        auth=("", MAILCHIMP_API_KEY),
        data=json.dumps(data)
    )
    return r.status_code, r.json()


def email_list_signup(request):
    form = EmailSignupForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            email_signup_qs = Signup.objects.filter(email=form.instance.email)
            if email_signup_qs.exists():
                messages.info(request, "You are already subscribed")
            else:
                subscribe(form.instance.email)
                form.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
# Create your views here.

def posts(request):
    posts = Post.objects.filter(active=True)
    trending_posts = Post.objects.filter(trending=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    form = EmailSignupForm()
    posts = myFilter.qs
    trending_posts = myFilter.qs
    # page = request.GET.get('page')

    # paginator = Paginator(posts, 10)

    # try:
    #     posts = paginator.page(page)
    # except PageNotAnInteger:
    #     posts = paginator.page(1)
    # except EmptyPage:
    #     posts = paginator.page(paginator.num_pages)
    
    context = {'posts': posts, 'trending_posts': trending_posts, 'myFilter': myFilter, 'form': form}
    return render(request, 'blog/blog.html', context)

def post(request, slug):
    post = Post.objects.get(slug=slug)
    related_posts = []
    form = EmailSignupForm()
    for tag in post.tags.all():
        related_post = Post.objects.filter(tags__name = tag)
        related_posts.append(related_post)
    # Comment section
    if request.method == 'POST':
        PostComment.objects.create(
            name=request.POST['name'],
            email=request.POST['email'],
            website=request.POST['website'],
            post=post,
            body=request.POST['comment']
        )
        messages.success(request, 'Your comment was sucessfully posted!')
        
        return redirect('post', slug=post.slug)

    context = {'post': post, 'related_posts': related_posts, 'form': form}
    return render(request, 'blog/post.html', context)

def tags(request):
    tags = Tag.objects.all()
    form = EmailSignupForm()
    context = {'tags': tags, 'form': form}
    return render(request, 'blog/tags.html', context)

def tagPage(request, tag):
    tag_posts = Post.objects.filter(tags__slug=tag)
    tag = Tag.objects.get(slug=tag)
    form = EmailSignupForm()
    context = {'posts': tag_posts, 'tag': tag, 'form': form}
    return render(request, 'blog/tag.html', context)


# CRUD VIEWS

@admin_only
@login_required(login_url='home')
def createPost(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')
    
    context = {'form': form}
    return render(request, 'blog/post_form.html', context)

@admin_only
@login_required(login_url='home')
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts')
        else:
            messages.info(request, "There is an error while updating")
        
    
    context = {'form': form}
    return render(request, 'blog/post_form.html', context)

def deletePost(request, slug):
    post = Post.objects.get(slug=slug)
    
    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    context = {'item': post}
    return render(request, 'blog/delete.html')

blog/templates/blog/blog.html
{% extends 'blog/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load readtime %}
{% block content %}

<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 100px;
		border-radius: 5px;
		padding: 5px;
		border:1px solid #888;
        margin-top: 1em;
	}
</style>

<div class="section pt-md-5">
    <div class="container">
        <!-- <div class="row justify-content-center mb-5">
            <div class="col-lg-7 text-center">
                <h2 style="font-weight: 700; font-size: 40px;">Latest Post</h2>
            </div>
        </div> -->
        <div class="row justify-content-center">    
            {% for post in posts|slice:":9" %}
            {% if post.latest %}
            <center>
            <h2 style="font-weight: 700; font-size: 40px; margin-bottom: 1em;">Latest Post</h2>
            </center>
            <div class="col-md-11 col-lg-12 pb-5" style="border-bottom: 1px solid rgba(0, 0, 0, 0.145);">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="img-thumbnail py-2" style="object-position: center;">
                            <a href="{% url 'post' post.slug %}">
                                <img class="img-fluid" src="{{ post.thumbnail.url }}" style="height: 24em; width: 100%;">
                            </a>
                        </div>
                    </div>
                <!-- <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <a href="{% url 'post' post.slug %}"><img src="{{ post.thumbnail.url }}" style="top: 0; left: 0; position: absolute; width: 100%; height: auto; border-radius: 5px; object-fit: cover; object-position: center center; max-width: 100%;"></a>
                    </div> -->
                    <div class="col-lg-4 pb-3">
                        <div class="row">
                            <!-- <div class="col" style="padding-right: 0; margin-bottom: 0.2em;"> -->
                                {% for tag in post.tags.all|slice:":1" %}
                                <a class="tag" href="{% url 'tag' tag.slug %}">
                                {{tag}}
                                </a>
                                {% endfor %}
                            <!-- </div> -->
                        </div>
                        <div class="row">
                            <h2 class="post-card-title"><a class='heading_url' href="{% url 'post' post.slug %}" style="text-decoration: none; color: inherit;">{{ post.headline }}</a></h1>
                        </div>
                        <div class="row">
                            <p class="post-card-text">
                                {{ post.sub_headline }}
                            </p>
                        </div>
                        <div class="row">
                            <span style="color: rgba(0, 0, 0, 0.576);">{{ post.created|date:"d M Y" }}<span style="padding: 3px;">•</span>{{ post.body|readtime }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="col-md-6 col-lg-4 pt-5 pb-4" style="border-bottom: 1px solid rgba(0, 0, 0, 0.145);">
                <div class="post-entry d-block">
                    <div class="thumbnail pb-4">
                        <a href="{% url 'post' post.slug %}">
                            <img class="img-fluid" src="{{ post.thumbnail.url }}" alt="Image" style="height: 17em;">
                        </a>
                    </div>
                    <div class="content">
                        <div class="row">
                            <div class="col" style="padding-right: 0; margin-bottom: 0.2em;">
                               
                                {% for tag in post.tags.all|slice:":1" %}
                                <a class="tag" href="{% url 'tag' tag.slug %}">
                                {{tag}}
                                </a>
                                {% endfor %}
                                
                            </div>
                        </div>
                        <div class="row">
                            <h2 class="post-card-title" style="font-size: 1.6rem; line-height: 1em;"><a href="{% url 'post' post.slug %}" class='heading_url' style="text-decoration: none; color: inherit;">{{ post.headline }}</a></h1>
                        </div>
                        <div class="row">
                            <p class="post-card-text" style="font-size: 1.1rem; line-height: 25.6px;">
                                {{ post.sub_headline }}
                            </p>
                        </div>
                        <div class="row">
                            <span style="color: rgba(0, 0, 0, 0.576);">{{ post.created|date:"d M Y" }}<span style="padding: 3px;">•</span>{{ post.body|readtime }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% empty %}
            <div class="col" style="text-align: center;">
                <h3>No posts found...</h3>
            </div>
            {% endfor %}
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Search</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body p-0">
                        <div class="container py-3">
                        <form id = "SearchForm" method="GET">
                            {{myFilter.form|crispy}}
                            <hr>
                            <input class="btn btn-primary" type="submit" value="Search">
                        </form>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
        </div>
    </div>
</div>

<!-- <div class="section pt-5">
    <div class="container">
        <div class="row g-5">
            {% for post in posts reversed %}
            <div class="col-lg-4">
                <div class="post-entry d-block">
                    <div class="thumbnail">
                        <a href="">
                            <img class="img-fluid" src="{{ post.thumbnail.url }}" alt="Image" style="height: 16em;">
                        </a>
                    </div>
                    <div class="content">
                        <div class="row">
                            <div class="col" style="padding-right: 0; margin-bottom: 0.2em;">
                                <a class="tag">
                                {% for tag in post.tags.all|slice:":1" %}
                                {{tag}}
                                {% endfor %}
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <h2 class="post-card-title" style="font-size: 1.6rem; line-height: 1em;"><a href="{% url 'post' post.slug %}" style="text-decoration: none; color: inherit;">{{ post.headline }}</a></h1>
                        </div>
                        <div class="row">
                            <p class="post-card-text" style="font-size: 1.1rem; line-height: 25.6px;">
                                {{ post.sub_headline }}
                            </p>
                        </div>
                        <div class="row">
                            <span>{{ post.created|date:"d M Y" }}<span style="padding: 3px;">•</span>{{ post.body|readtime }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div> -->
<!-- <div class="main-container">
    <h1>Posts</h1>
    {% if request.user.is_staff %}
        <a class="btn btn-warning" href="{% url 'create_post' %}">Create Post</a>
    {% endif %}
    <form id = "SearchForm" method="GET">
        {{myFilter.form|crispy}}
        <input class="btn btn-primary" type="submit" value="Search">
    </form>
    <br>
    <div class="post-wrapper">
        {% for post in posts %}
        <div>
            <div class="post">
                <img class='thumbnail' src='{{ post.thumbnail.url }}'>
                <div class="post-preview">
                    <h6 class="post-title">{{post.headline}}</h6>
                    <p class="post-intro">{{post.sub_headline}}</p>
                    <a href="{% url 'post' post.slug %}">Read More</a>

                    {% if request.user.is_staff %}
                        | <a href="{% url 'update_post' post.slug %}">Edit</a>
                        | <a href="{% url 'delete_post' post.slug %}">Delete</a>
                    {% endif %}
                    <hr>
                    {% for tag in post.tags.all %}
                        <span class="tag">{{tag}}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% empty %}
            <h3>No posts found...</h3>
        {% endfor %}
    </div>

    <div class="row">
        {% if posts.has_other_pages %}
            <ul class="pagination">
                
                {% if posts.has_previous %}
                    <li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

                    <li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
                {% endif %}

                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="page-item"><a class="active page-link">{{i}}</a></li>
                    {% else %}
                        <li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% endif %}
                {% endfor %}

                {% if posts.has_next %}
                    <li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{post.paginator.num_pages}}" class="page-link">Last</a></li>
                    <li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{post.next_page_number}}" class="page-link">&raquo</a></li>
                {% endif %}

            </ul>
        {% endif %}
    </div>
</div> -->




<!-- Button trigger modal -->

  
  <!-- Modal -->

  
<script type="text/javascript">
    let searchForm = document.getElementById('searchForm')
    let pageLinks = document.getElementsByClassName('page-link')

    for(var i=0; pageLinks.length > 1; i++) {

        pageLinks[i].addEventListener('click', function(e){
            e.preventDefault()[i]
            let = this.dataset.page
            console.log('Page:', page)
            searchForm.innerHTML += `<input value="${page}" name='page' hidden>`
            searchForm.submit()
        })
    }
</script>

{% endblock content %}

blog/templates/blog/delete.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<div class="main-container">
    <form method="POST" action="">
        {% csrf_token %}

        <p>Are you sure you want to delete {{item}}? </p>
        <a class="btn btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
</div>
{% endblock content %}

blog/templates/blog/post.html
{% extends 'blog/main.html' %}
{% load static %}
{% load readtime %}
{% block content %}


<style type="text/css">
    .comments-wrapper{
        margin-top: 50px;
        padding: 10px;
        border: 1px solid var(--borderColor);
        -webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
        -moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
        box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
    }

    .comment{
        display: flex;
        padding: 15px;
    }

    .comment-author{
        font-weight: 400;
        font-size: 18px;
		color: rgb(0, 0, 0) !important;
        margin: 2px;
    }
    .comment-body{
        font-size: 14px;
        color: rgb(75, 75, 75);
    }
    .author-pic1{
        width: 40px !important;
        height: 40px;
        border-radius: 100%;
        margin-right: 10px
    }
</style>
<div class="section post-section py-5">
    <div class="container">

            {% if request.user.is_staff %}
            <div class="row mb-5 mt-0">
                <div>
                <a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
                <a class="btn btn-sm btn-primary" href="{% url 'update_post' post.slug %}">Edit</a>
                <a class="btn btn-sm btn-primary" href="{% url 'delete_post' post.slug %}">Delete</a>
                </div>
            </div>
            {% endif %}

        <div class="row justify-content-center">
            <div class="col-12 col-sm-8 justify-content-center">
                <div class="text-center">
                    <img src="{% static 'images/Amit.jpg' %}" alt="Image" class="author-pic rounded-circle mx-auto">
                </div>
                <span class="d-block text-center" style="font-size: 1.3rem; color: rgb(105, 105, 105);">{{ post.author.get_full_name }}</span>
                <span class="date d-block text-center small text-uppercase text-black-50 mb-4 fs-5">{{ post.created|date:"d M Y" }}</span>
                <div class="text-center">
                    <ul class="navbar-nav flex-row d-none d-md-flex justify-content-center">
                        {% for tag in post.tags.all %}
                        {% if forloop.last %}
                        <li class="nav-item me-3 me-lg-1">
                            <a class="tag nav-link" style="font-size: 0.9rem; font-weight: 700;" target="_blank" href="{% url 'tag' tag.slug %}">
                                <span>{{ tag }}</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item d-flex me-3 me-lg-1">
                            <a class="tag nav-link" style="font-size: 0.9rem; font-weight: 700;" target="_blank" href="#">
                                <span>{{ tag }}</span>
                            </a>
                            <span class="ps-2 pe-1" style="padding-top: 6px;">•</span>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <h2 class="heading text-center">{{post.headline}}</h2>
                <p class="text-center mb-4" style="font-size: 1.25rem; font-weight: 400; color: rgb(105, 105, 105);">{{post.sub_headline}}</p>
                <img src="{{ post.thumbnail.url }}" alt="Image" style="width: 100%;" class="img-fluid rounded mb-4">
                <div class="row">{{ post.body|safe }}</div>
                <div class="row mt-5 pt-5 border-top">
                    <div class="col-12">
                        <span class="fw-bold text-black small mb-1">Share</span>
                        <ul class="social list-unstyled">
                            <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                            <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                            <li><a href="#"><i class="bi bi-linkedin"></i></a></li>
                            <!-- <li><a href="#"><i class="bi bi-pinterest"></i></a></li> -->
                        </ul>
                    </div>
                </div>
                <div class="comments-wrapper">
                    <h5>Comments: {{post.postcomment_set.all.count}}</h5>
                    <hr>
                    <form action="" method="POST" class="p-5 bg-light">
                        {% csrf_token %}
                        <div class="form-group py-2">
                            <label for="name">Name *</label>
                            <input type="text" class="form-control" name="name" required>
                        </div>
                        <div class="form-group py-2">
                            <label for="email">Email *</label>
                            <input type="email" class="form-control" name="email" required>
                        </div>
                        <div class="form-group py-2">
                            <label for="website">Website</label>
                            <input type="url" class="form-control" name="website">
                        </div>
                        <div class="form-group py-2">
                            <label for="message">Message *</label>
                            <textarea name="comment" cols="30" rows="10" class="form-control" required></textarea>
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Post Comment" class="btn btn-primary rounded-pill py-3" style="background-color: rgb(38, 166, 237); border-color: rgb(38, 166, 237); font-size: 14px; letter-spacing: 0.2rem; text-transform: uppercase;">
                        </div>
                    </form>
                    <hr>
                    {% for comment in post.postcomment_set.all %}
                        <div class="comment">
                            <img class="author-pic1" src="{% static 'images/user.png' %}" />
                            <div>
                                <p class="comment-author">
                                    {% if comment.website %}
                                    <a href="{{ comment.website }}" target="_blank" style="color: inherit;">{{comment.name}}</a>
                                    {% else %}
                                    {{comment.name}}
                                    {% endif%}
                                </p>
                                <p style="color: rgb(136, 136, 136); font-size: 15px; margin-bottom: 0.5rem;">{{comment.created|date:"M-d-Y"}}</p>
                                <p class="comment-body">{{comment.body}}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section pt-5">
    <div class="container">
        <div class="row justify-content-center px-2">
            <div class="col-lg-11">
                <h2 class="m-0" style="font-size: 3rem; font-weight: 700;">Related</h2>
            </div>
        </div>
        {% for related_post in related_posts %}
        {% for other_post in related_post%}
        {% if other_post != post %}
        <div class="row justify-content-center p-2">
            <div class="col-lg-12">
                <div class="row justify-content-center">
                    <div class="col-lg-4">
                        <div class="img-thumbnail py-2" style="object-position: center;">
                            <a href="{% url 'post' other_post.slug %}">
                                <img class="img-fluid" src="{{ other_post.thumbnail.url }}" style="height: auto;">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-7 pb-3">
                        <div class="row">
                                <a class="tag">
                                {% for tag in other_post.tags.all|slice:":1" %}
                                {{tag}}
                                {% endfor %}
                                </a>
                        </div>
                        <div class="row">
                            <h2 class="post-card-title" style="font-size: 1.8rem;"><a href="{% url 'post' other_post.slug %}" style="text-decoration: none; color: inherit;">{{ other_post.headline }}</a></h1>
                        </div>
                        <div class="row">
                            <p class="post-card-text">
                                {{ other_post.sub_headline }}
                            </p>
                        </div>
                        <div class="row">
                            <span style="color: rgba(0, 0, 0, 0.576);">{{ other_post.created|date:"d M Y" }}<span style="padding: 3px;">•</span>{{ other_post.body|readtime }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body p-0">
            <div class="container py-3">
                <h2 class="heading">Search feature only works in blog page.</h2>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
    #div_id_tags > div{
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
    }
</style>
<div class="container">
    <a class="btn btn-sm btn-primary" href="{% url 'posts' %}" style="margin: 1em 0; padding-left: 5px;">&laquo Back to Posts</a>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Submit Post">
    </form>
</div>
{% endblock content %}